name: meta_elham_flutter
description: "Meta Elham is an interactive educational platform for children with autism. The app uses AI-driven features to enhance personalized learning experiences, incorporating interactive games, video tutorials, and initial AI-based assessments to support both children and educators."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_otp_text_field: ^1.2.0
  supabase_flutter: ^2.8.0
  fl_chart: ^0.69.0
  get: ^4.6.1
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  file_picker: ^8.1.3
  dio: ^5.7.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/images/background/
    - assets/images/logo/
    - assets/images/avatars/
